services:
  db:
    image: postgres:15.2-alpine
    container_name: polar-postgres
    restart: always
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: polardb_catalog
    ports:
        - 5432:5432